-- vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
-- vim.api.nvim_create_autocmd({
--   "BufWritePre",
--   "plugins-setup.lua",
--   "source <afile> | PackerSync",
--   { augroup = augroup, buffer = bufnr },
-- })
